### ISSUE TITLE
what is the use of vendor/bin/rocinante theme:regen

### ISSUE THREAD

**Issue by deepaksinghdhanik** [alpineio/quixote#2]
Hi I am going to use quixote sytem , but I don't know what is the use of this line .. it would be greate if you little explain this.

vendor/bin/rocinante theme:regen "Super Awesome Theme" ./ renames Alpine.IO's base Underscores theme in the current directory.

Thanks 
-- Deepak

**Comment by moneal** [comment]
This command renames a bunch of the functions in the base underscores theme. This is used to namespace the new themes functions, add correct text domain information and update the style.css
